@url_dev=http://localhost:5000/

## homepage
GET http://localhost:5000/

## get api

###
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: fsdfhskjfhwefjasdfaksdfjlasd

{
    "name": "Shop Minh Hy",
    "email": "shopminhhy@gmail.com",
    "password": "abc123"
}
